-d /home/sdev/Workspace/GowinEDA/Gowin_GW1NR-9/VerilogBasics/impl/gwsynthesis/project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/sdev/Workspace/GowinEDA/Gowin_GW1NR-9/VerilogBasics/src/HwSetup.cst
-cfg /home/sdev/Workspace/GowinEDA/Gowin_GW1NR-9/VerilogBasics/impl/pnr/device.cfg
-sdc /home/sdev/Workspace/GowinEDA/Gowin_GW1NR-9/VerilogBasics/src/VerilogBasics.sdc
-bit
-tr
-ph
-timing
-cst_error
