-d /home/sdev/Workspace/GowinEDA/GW1N-9C/VerilogBasics/impl/gwsynthesis/project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/sdev/Workspace/GowinEDA/TangNano-9K-example-main/led/src/9K_LED_project.cst
-cfg /home/sdev/Workspace/GowinEDA/GW1N-9C/VerilogBasics/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
