#!/bin/bash

echo Building FPGA project

log="commandLog.txt"

if test -f "$log"; then
    rm $log
fi

gw_sh projectConf.tcl | tee $log

SuccessOutputString="Power analysis completed"

if grep -q "$SuccessOutputString" "$log" ; then
    printf "\nCOMPILATION SUCCESSFUL! \n"
    printf "Deploying to FPGA... \n\n"
    fpgaLoader=/home/sdev/Apps/OpenFpgaLoader/bin/openFPGALoader
    $fpgaLoader -m -b tangnano9k impl/pnr/project.fs -v
else 
    printf "\nCOMPILATION FAILED! \n"
fi



